const crypto = require('crypto');

const { connectDatabase } = require('../config/db');
const { ROLES } = require('../constants/roles');
const ActivityLog = require('../models/activity-log.model');
const AuthSession = require('../models/auth-session.model');
const Customer = require('../models/customer.model');
const Expense = require('../models/expense.model');
const InventoryStock = require('../models/inventory-stock.model');
const Notification = require('../models/notification.model');
const PosDraftOrder = require('../models/pos-draft-order.model');
const Product = require('../models/product.model');
const PurchaseOrder = require('../models/purchase-order.model');
const Sale = require('../models/sale.model');
const Settings = require('../models/settings.model');
const StockMovement = require('../models/stock-movement.model');
const Supplier = require('../models/supplier.model');
const User = require('../models/user.model');
const Warehouse = require('../models/warehouse.model');

const TOTAL_ROWS = 25;

function randomChoice(values) {
  return values[Math.floor(Math.random() * values.length)];
}

function randomNumber(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function roundCurrency(value) {
  return Number(value.toFixed(2));
}

function buildProduct(index) {
  const categories = ['Audio', 'Mobile', 'Accessories', 'Computers', 'Television'];
  const cp = randomNumber(500, 30000);
  const sp = cp + randomNumber(120, 8000);
  const stock = randomNumber(20, 200);

  return {
    name: `Bulk Product ${index + 1}`,
    category: randomChoice(categories),
    stock,
    lowStockLimit: randomNumber(4, 25),
    cp,
    sp,
    tags: ['bulk', 'seed', `group-${(index % 5) + 1}`],
    supplier: {
      name: `Supplier ${(index % 10) + 1}`,
      email: `supplier${(index % 10) + 1}@bulk.local`,
      phone: `+9198${String(index).padStart(8, '0')}`,
      referenceCode: `SUP-${index + 1}`,
    },
    warrantyMonths: randomNumber(0, 24),
    image: { url: '', publicId: '' },
  };
}

async function seedBulk() {
  await connectDatabase();

  await Promise.all([
    ActivityLog.deleteMany({}),
    AuthSession.deleteMany({}),
    Customer.deleteMany({}),
    Expense.deleteMany({}),
    InventoryStock.deleteMany({}),
    Notification.deleteMany({}),
    PosDraftOrder.deleteMany({}),
    PurchaseOrder.deleteMany({}),
    Sale.deleteMany({}),
    Settings.deleteMany({}),
    StockMovement.deleteMany({}),
    Supplier.deleteMany({}),
    Product.deleteMany({}),
    Warehouse.deleteMany({}),
    User.deleteMany({}),
  ]);

  const users = [];

  const admin = await User.create({
    name: 'Admin User',
    email: 'admin@mujahidgoods.com',
    password: 'Admin@123',
    role: ROLES.ADMIN,
  });
  users.push(admin);

  const manager = await User.create({
    name: 'Manager User',
    email: 'manager@mujahidgoods.com',
    password: 'Manager@123',
    role: ROLES.MANAGER,
  });
  users.push(manager);

  const staff = await User.create({
    name: 'Staff User',
    email: 'staff@mujahidgoods.com',
    password: 'Staff@123',
    role: ROLES.STAFF,
  });
  users.push(staff);

  for (let index = 0; index < TOTAL_ROWS - 3; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const user = await User.create({
      name: `Bulk User ${index + 1}`,
      email: `bulk-user-${index + 1}@mujahidgoods.local`,
      password: 'Bulk@123',
      role: randomChoice([ROLES.ADMIN, ROLES.MANAGER, ROLES.STAFF]),
      active: index % 9 !== 0,
    });

    users.push(user);
  }

  const warehouses = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const warehouse = await Warehouse.create({
      name: `Warehouse ${index + 1}`,
      address: `Zone ${index + 1}, Industrial Area`,
      contactPhone: `+9199${String(index).padStart(8, '0')}`,
      isDefault: index === 0,
      active: true,
    });

    warehouses.push(warehouse);
  }

  const suppliers = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const supplier = await Supplier.create({
      name: `Bulk Supplier ${index + 1}`,
      email: `bulk-supplier-${index + 1}@suppliers.local`,
      phone: `+9188${String(index).padStart(8, '0')}`,
      address: `Supplier Road ${index + 1}`,
      paymentTermsDays: randomNumber(7, 60),
      openingBalance: randomNumber(0, 10000),
      notes: 'Generated by seed-bulk',
      active: index % 11 !== 0,
    });

    suppliers.push(supplier);
  }

  const products = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const product = await Product.create(buildProduct(index));
    products.push(product);
  }

  const inventoryStocks = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    const product = products[index % products.length];
    const warehouse = warehouses[index % warehouses.length];

    // eslint-disable-next-line no-await-in-loop
    const stock = await InventoryStock.create({
      product: product._id,
      warehouse: warehouse._id,
      quantity: randomNumber(10, 140),
      reservedQuantity: randomNumber(0, 6),
    });

    inventoryStocks.push(stock);
  }

  const customers = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const customer = await Customer.create({
      name: `Bulk Customer ${index + 1}`,
      email: `bulk-customer-${index + 1}@mail.local`,
      phone: `+9177${String(index).padStart(8, '0')}`,
      address: `Street ${index + 1}, City`,
      notes: 'Generated for API checks',
      tags: ['bulk', index % 2 === 0 ? 'vip' : 'regular'],
      loyaltyPoints: randomNumber(0, 400),
      creditBalance: randomNumber(0, 5000),
      totalSpent: randomNumber(0, 120000),
      totalPurchases: randomNumber(0, 50),
      active: true,
    });

    customers.push(customer);
  }

  const sales = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    const product = products[index % products.length];
    const quantity = randomNumber(1, 3);
    const subtotal = roundCurrency(product.sp * quantity);
    const taxRate = 18;
    const tax = roundCurrency((subtotal * taxRate) / 100);
    const total = roundCurrency(subtotal + tax);
    const profit = roundCurrency((product.sp - product.cp) * quantity);
    const discountAmount = index % 4 === 0 ? roundCurrency(subtotal * 0.1) : 0;
    const adjustedTotal = roundCurrency(Math.max(total - discountAmount, 0));

    // eslint-disable-next-line no-await-in-loop
    const sale = await Sale.create({
      items: [
        {
          product: product._id,
          name: product.name,
          category: product.category,
          sku: product.sku,
          quantity,
          price: product.sp,
          costPrice: product.cp,
          subtotal,
          profit,
          image: product.image?.url || '',
        },
      ],
      subtotal,
      taxRate,
      tax,
      total: adjustedTotal,
      profit,
      paymentMethod: randomChoice(['cash', 'card', 'upi']),
      discountType: discountAmount ? 'percent' : 'none',
      discountValue: discountAmount ? 10 : 0,
      discountAmount,
      amountPaid: adjustedTotal,
      balanceDue: 0,
      status: 'completed',
      payments: [
        {
          method: randomChoice(['cash', 'card', 'upi']),
          amount: adjustedTotal,
          reference: `PAY-${index + 1}`,
          paidAt: new Date(),
        },
      ],
      customerName: customers[index % customers.length].name,
      customerPhone: customers[index % customers.length].phone,
      customer: customers[index % customers.length]._id,
      warehouse: warehouses[0]._id,
      createdBy: admin._id,
      salesperson: users[(index % (users.length - 1)) + 1]._id,
      notes: 'Generated bulk sale',
      receiptMeta: {
        shopName: 'Mujahid Electronic Goods',
        address: 'Bulk Seed Address',
        contactPhone: '+91 90000 00000',
        contactEmail: 'sales@mujahidgoods.local',
        taxRate,
      },
      date: new Date(Date.now() - index * 86400000),
    });

    sales.push(sale);
  }

  const expenses = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const expense = await Expense.create({
      title: `Bulk Expense ${index + 1}`,
      category: randomChoice(['Utilities', 'Maintenance', 'Marketing', 'Rent']),
      amount: randomNumber(500, 15000),
      paymentMethod: randomChoice(['cash', 'bank', 'upi']),
      paidTo: `Vendor ${index + 1}`,
      notes: 'Generated by seed-bulk',
      expenseDate: new Date(Date.now() - index * 3600000),
      createdBy: admin._id,
    });

    expenses.push(expense);
  }

  const purchaseOrders = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    const product = products[index % products.length];
    const quantity = randomNumber(2, 15);
    const unitCost = randomNumber(200, 7000);
    const subtotal = roundCurrency(quantity * unitCost);
    const taxRate = 5;
    const taxAmount = roundCurrency((subtotal * taxRate) / 100);
    const total = roundCurrency(subtotal + taxAmount);
    const amountPaid = index % 3 === 0 ? roundCurrency(total * 0.5) : total;

    // eslint-disable-next-line no-await-in-loop
    const po = await PurchaseOrder.create({
      supplier: suppliers[index % suppliers.length]._id,
      warehouse: warehouses[index % warehouses.length]._id,
      items: [
        {
          product: product._id,
          name: product.name,
          sku: product.sku,
          quantity,
          unitCost,
          subtotal,
        },
      ],
      subtotal,
      taxRate,
      taxAmount,
      total,
      amountPaid,
      amountDue: roundCurrency(Math.max(total - amountPaid, 0)),
      expectedDate: new Date(Date.now() + randomNumber(1, 20) * 86400000),
      status: randomChoice(['draft', 'ordered', 'received']),
      notes: 'Generated bulk purchase order',
      orderedAt: new Date(Date.now() - index * 43200000),
      receivedAt: index % 4 === 0 ? new Date() : null,
      createdBy: admin._id,
    });

    purchaseOrders.push(po);
  }

  const posDrafts = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    const product = products[index % products.length];

    // eslint-disable-next-line no-await-in-loop
    const draft = await PosDraftOrder.create({
      title: `Draft #${index + 1}`,
      items: [
        {
          productId: String(product._id),
          name: product.name,
          price: product.sp,
          quantity: randomNumber(1, 2),
        },
      ],
      customerName: customers[index % customers.length].name,
      customerPhone: customers[index % customers.length].phone,
      paymentMethod: randomChoice(['cash', 'upi', 'card']),
      taxRate: 18,
      discountType: randomChoice(['none', 'flat', 'percent']),
      discountValue: randomNumber(0, 10),
      notes: 'Generated draft',
      createdBy: users[index % users.length]._id,
    });

    posDrafts.push(draft);
  }

  const notifications = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const notification = await Notification.create({
      type: randomChoice(['inventory-low', 'sale-completed', 'system']),
      level: randomChoice(['info', 'warning', 'success']),
      title: `Bulk Notification ${index + 1}`,
      message: `Generated notification message ${index + 1}`,
      recipient: users[index % users.length]._id,
      read: index % 3 === 0,
      channels: ['in-app'],
      metadata: { source: 'seed-bulk', index },
    });

    notifications.push(notification);
  }

  const activityLogs = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const log = await ActivityLog.create({
      user: users[index % users.length]._id,
      eventType: randomChoice(['login', 'logout', 'product_created', 'stock_transfer']),
      category: randomChoice(['auth', 'inventory', 'sales']),
      status: randomChoice(['success', 'failure']),
      message: `Bulk activity log ${index + 1}`,
      metadata: { source: 'seed-bulk', index },
      ipAddress: `192.168.1.${index + 1}`,
      userAgent: 'bulk-seed-script',
    });

    activityLogs.push(log);
  }

  const sessions = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    const user = users[index % users.length];
    // eslint-disable-next-line no-await-in-loop
    const session = await AuthSession.create({
      user: user._id,
      refreshTokenHash: crypto.createHash('sha256').update(`refresh-${index}`).digest('hex'),
      userAgent: 'bulk-seed-script',
      ipAddress: `10.0.0.${index + 1}`,
      deviceLabel: `bulk-device-${index + 1}`,
      tokenVersion: user.tokenVersion,
      lastUsedAt: new Date(),
      revokedAt: index % 8 === 0 ? new Date() : null,
      revokedReason: index % 8 === 0 ? 'seed-revoked' : '',
      expiresAt: new Date(Date.now() + randomNumber(5, 40) * 86400000),
    });

    sessions.push(session);
  }

  const settings = [];
  // eslint-disable-next-line no-await-in-loop
  const defaultSettings = await Settings.create({
    shopCode: 'default',
    shopName: 'Mujahid Electronic Goods',
    address: 'Main Market, Kolkata',
    contactPhone: '+91 90000 00000',
    contactEmail: 'admin@mujahidgoods.com',
    taxRate: 18,
    currency: 'INR',
    darkMode: false,
    enableLowStockPopup: true,
    enableEmailAlerts: true,
    lowStockEmail: 'alerts@mujahidgoods.local',
    receiptFooter: 'Thank you for shopping with us',
  });
  settings.push(defaultSettings);

  for (let index = 1; index < TOTAL_ROWS; index += 1) {
    // eslint-disable-next-line no-await-in-loop
    const config = await Settings.create({
      shopCode: `shop-${index}`,
      shopName: `Mujahid Branch ${index}`,
      address: `Branch Address ${index}`,
      contactPhone: `+91 90123${String(index).padStart(5, '0')}`,
      contactEmail: `branch-${index}@mujahidgoods.local`,
      taxRate: randomChoice([5, 12, 18]),
      currency: 'INR',
      darkMode: index % 2 === 0,
      enableLowStockPopup: true,
      enableEmailAlerts: index % 3 === 0,
      lowStockEmail: `alerts-branch-${index}@mujahidgoods.local`,
      receiptFooter: `Thank you from branch ${index}`,
    });

    settings.push(config);
  }

  const stockMovements = [];
  for (let index = 0; index < TOTAL_ROWS; index += 1) {
    const product = products[index % products.length];
    const warehouse = warehouses[index % warehouses.length];
    const quantity = randomNumber(1, 12);

    // eslint-disable-next-line no-await-in-loop
    const movement = await StockMovement.create({
      product: product._id,
      warehouse: warehouse._id,
      fromWarehouse: warehouse._id,
      toWarehouse: warehouses[(index + 1) % warehouses.length]._id,
      movementType: randomChoice(['transfer_in', 'transfer_out', 'adjustment', 'sale']),
      quantity,
      beforeQuantity: randomNumber(10, 200),
      afterQuantity: randomNumber(10, 200),
      actor: users[index % users.length]._id,
      referenceType: randomChoice(['purchase-order', 'sale', 'inventory-adjustment']),
      referenceId: `REF-${index + 1}`,
      notes: 'Generated stock movement',
      metadata: { source: 'seed-bulk', index },
    });

    stockMovements.push(movement);
  }

  const summary = {
    users: users.length,
    warehouses: warehouses.length,
    suppliers: suppliers.length,
    products: products.length,
    inventoryStocks: inventoryStocks.length,
    customers: customers.length,
    sales: sales.length,
    expenses: expenses.length,
    purchaseOrders: purchaseOrders.length,
    posDrafts: posDrafts.length,
    notifications: notifications.length,
    activityLogs: activityLogs.length,
    authSessions: sessions.length,
    settings: settings.length,
    stockMovements: stockMovements.length,
  };

  // eslint-disable-next-line no-console
  console.log('Bulk seed complete');
  // eslint-disable-next-line no-console
  console.table(summary);
  process.exit(0);
}

seedBulk().catch((error) => {
  // eslint-disable-next-line no-console
  console.error('Bulk seed failed', error);
  process.exit(1);
});
